# Generated by Django 2.2.5 on 2019-09-06 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 6, 18, 14, 46, 111020, tzinfo=utc), verbose_name='date published'),
        ),
    ]
